// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfsq3uuYJvy18rt9yfYn_R4e8pUBw_bMg',
    appId: '1:989623737343:web:f2376b4c4e9baaf76ae5ca',
    messagingSenderId: '989623737343',
    projectId: 'deshcam-e3ef5',
    authDomain: 'deshcam-e3ef5.firebaseapp.com',
    storageBucket: 'deshcam-e3ef5.appspot.com',
    measurementId: 'G-22DV0VYWPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVYtt2L2qOZr64ZCKuY0Rkb0QWlBQwKTc',
    appId: '1:989623737343:android:dfeb04e7b5ff21e66ae5ca',
    messagingSenderId: '989623737343',
    projectId: 'deshcam-e3ef5',
    storageBucket: 'deshcam-e3ef5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfBLxxbYwLDRPmwgjue304cnHy9e76ijk',
    appId: '1:989623737343:ios:335950487ec6eb6f6ae5ca',
    messagingSenderId: '989623737343',
    projectId: 'deshcam-e3ef5',
    storageBucket: 'deshcam-e3ef5.appspot.com',
    iosBundleId: 'com.vearshop.deshcam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfBLxxbYwLDRPmwgjue304cnHy9e76ijk',
    appId: '1:989623737343:ios:335950487ec6eb6f6ae5ca',
    messagingSenderId: '989623737343',
    projectId: 'deshcam-e3ef5',
    storageBucket: 'deshcam-e3ef5.appspot.com',
    iosBundleId: 'com.vearshop.deshcam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfsq3uuYJvy18rt9yfYn_R4e8pUBw_bMg',
    appId: '1:989623737343:web:c7e34980251d54d56ae5ca',
    messagingSenderId: '989623737343',
    projectId: 'deshcam-e3ef5',
    authDomain: 'deshcam-e3ef5.firebaseapp.com',
    storageBucket: 'deshcam-e3ef5.appspot.com',
    measurementId: 'G-EMKL95B64F',
  );
}
